package fr.asterox.NotesCentral.service;

import java.util.List;
import java.util.Optional;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import fr.asterox.NotesCentral.bean.Note;
import fr.asterox.NotesCentral.proxy.PatientManagementProxy;
import fr.asterox.NotesCentral.repository.INoteRepository;
import fr.asterox.NotesCentral.util.NoNoteException;
import fr.asterox.NotesCentral.util.NoPatientException;

@Service
public class NoteService implements INoteService {
	@Autowired
	private INoteRepository noteRepository;

	@Autowired
	private PatientManagementProxy patientManagementProxy;

	private static final Logger LOGGER = LogManager.getLogger(NoteService.class);

	@Override
	public Note addNote(Note note) {
		// TODO : autogeneratedId
		if (!patientManagementProxy.askExistenceOfPatient(note.getPatientId())) {
			LOGGER.info("The requested patient does not exist.");
			throw new NoPatientException("This patient does not exist.");
		}

		LOGGER.info("Adding new note to patient with id : " + note.getPatientId());
		return noteRepository.save(note);
	}

	@Override
	public Note findById(Long noteId) {
		Optional<Note> note = noteRepository.findById(noteId);

		if (note.isEmpty()) {
			LOGGER.info("The requested note does not exist.");
			throw new NoNoteException("This note does not exist.");
		}

		LOGGER.info("Getting note");
		return note.get();
	}

	@Override
	public List<Note> findPatientNotes(Long patientId) {
		List<Note> patientNotes = noteRepository.findAllByPatientId(patientId);

		if (patientNotes.isEmpty()) {
			LOGGER.info("This patient has no note.");
			throw new NoNoteException("This patient has no note.");
		}

		LOGGER.info("Getting patient notes");
		return patientNotes;
	}

	@Override
	public Note updateNote(Long noteId, Note note) {
		Optional<Note> searchedNote = noteRepository.findById(noteId);

		if (searchedNote.isEmpty()) {
			LOGGER.info("The requested note does not exist.");
			throw new NoNoteException("This note does not exist.");
		}
		LOGGER.info("Updating note");
		return noteRepository.save(note);
	}

	@Override
	public void deleteNote(Long noteId) {
		Optional<Note> note = noteRepository.findById(noteId);

		if (note.isEmpty()) {
			LOGGER.info("The requested note does not exist.");
			throw new NoNoteException("This note does not exist.");
		}

		LOGGER.info("Deleting note");
		noteRepository.deleteById(noteId);
	}

	public INoteRepository setNoteRepository(INoteRepository noteRepository) {
		return this.noteRepository = noteRepository;
	}

	public PatientManagementProxy setPatientManagementProxy(PatientManagementProxy patientManagementProxy) {
		return this.patientManagementProxy = patientManagementProxy;
	}
}
